'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { PRODUCT_DATA } from '@/data/products';
import { illSecAbout, illSecBrand, illSecCareers, illSecContact, illSecEnterprise, illSecHelp, illSecLeadership, illSecPress, illSecSecurity, illSecSitemap } from '@/data/illustrations';
import Footer from '@/components/layout/Footer';

interface GenericPageProps { title: string; type: string; }
type PageInfo = { accent: string; intro: string; sections: { heading: string; body: string }[]; illustration?: string };
const PAGE_CONTENT: Record<string, PageInfo> = {
  about: { accent: '#4da8ff', illustration: illSecAbout, intro: 'A technology company building digital products and helping organizations turn useful ideas into working experiences.', sections: [{ heading: 'Who we are', body: 'We build digital products, websites, web applications, Android applications, iOS applications, cross-platform mobile applications, e-commerce platforms, AI-focused products, and custom digital solutions.' }, { heading: 'The founder', body: 'AM Kaweesi is the Founder & Technology Builder behind our products. We build our own products while also helping businesses and organizations ship useful digital experiences.' }, { heading: 'How we build', body: 'We start with the problem and the people who need the solution. From there, product thinking, design, and engineering stay in one close loop.' }] },
  leadership: { accent: '#9d8cff', illustration: illSecLeadership, intro: 'Independent teams, clear ownership, and the space to make the best decisions for the people using each product.', sections: [{ heading: 'Our philosophy', body: 'We structure our teams like independent startups. Each product has its own leadership, engineering, and design resources, giving it autonomy to move fast.' }, { heading: 'Leadership team', body: 'Our leadership brings experience in consumer internet, enterprise software, and applied AI. We are united by a shared vision for well-designed digital tools.' }, { heading: 'Our values', body: 'Privacy is a right. Speed is respect for the user’s time. Security is the floor, not the ceiling.' }] },
  enterprise: { accent: '#4da8ff', illustration: illSecEnterprise, intro: 'A product foundation with the controls, support, and flexibility serious organizations need.', sections: [{ heading: 'Enterprise grade products', body: 'We offer dedicated enterprise plans with advanced security controls, custom domain support, audit logging, and dedicated infrastructure.' }, { heading: 'Security & compliance', body: 'Enterprise accounts include compliance reports, data residency options, single tenant deployments, and custom data retention policies.' }, { heading: 'Custom integrations', body: 'Our enterprise APIs connect with identity providers, HR systems, and business tools. SAML SSO, SCIM provisioning, and a management API are included.' }] },
  security: { accent: '#8be7c4', illustration: illSecSecurity, intro: 'Security is not an add-on at AfuChat. It is the foundation every product is built on.', sections: [{ heading: 'Security by design', body: 'We use AES 256 encryption for data at rest, TLS 1.3 for data in transit, and zero knowledge architecture where applicable.' }, { heading: 'Two factor authentication', body: 'Every account supports TOTP based two factor authentication and hardware security keys. For enterprise accounts, 2FA can be enforced across the organization.' }, { heading: 'Vulnerability disclosure', body: 'We operate a responsible disclosure program for security researchers and commit to acknowledging reports within 24 hours.' }] },
  contact: { accent: '#8be7c4', illustration: illSecContact, intro: 'Whether you have a product question, a partnership idea, or a project to build, our team is here.', sections: [{ heading: 'Get in touch', body: 'We would love to hear from you. Tell us what you are trying to make and we will start with the problem.' }, { heading: 'Support', body: 'For product support, visit our Help Center. Our support team responds within 4 hours on business days.' }, { heading: 'Business inquiries', body: 'For partnership, enterprise, and media inquiries, reach out at business@afuchat.com.' }] },
  careers: { accent: '#8be7c4', illustration: illSecCareers, intro: 'Build digital products used by millions with people who care about craft, speed, and the details.', sections: [{ heading: 'Build the future', body: 'We are looking for engineers, designers, and operators who want to own meaningful work.' }, { heading: 'How we work', body: 'Small autonomous teams own products end to end. We favor shipping over process and give people real ownership early.' }, { heading: 'Benefits', body: 'Competitive pay and equity, covered health coverage, flexible time off, a learning budget, and access to our premium products.' }] },
  press: { accent: '#4da8ff', illustration: illSecPress, intro: 'Press resources, product context, and a direct line to the people building AfuChat.', sections: [{ heading: 'Media resources', body: 'Find logo assets, product screenshots, and executive bios in our press kit. For interview requests, reach out to communications.' }, { heading: 'Recent coverage', body: 'AfuChat has been featured in technology and business publications covering our approach to focused digital tools.' }, { heading: 'Press contact', body: 'For media inquiries, email press@afuchat.com. We aim to respond within one business day.' }] },
  brand: { accent: '#9d8cff', illustration: illSecBrand, intro: 'A clear identity for a family of products with distinct personalities.', sections: [{ heading: 'Our visual identity', body: 'The AfuChat brand is built around clarity. Our logo, color palette, and typography are designed to feel consistent across our product suite.' }, { heading: 'Logo usage', body: 'Please do not alter, recolor, or distort the AfuChat logo. Maintain clear space around it equal to the height of the logomark.' }, { heading: 'Download assets', body: 'Approved logos, color specifications, and typography guidelines are available for partners and press at brand@afuchat.com.' }] },
  help: { accent: '#8be7c4', illustration: illSecHelp, intro: 'Answers for account setup, billing, security, and troubleshooting across every AfuChat product.', sections: [{ heading: 'How can we help?', body: 'Our Help Center covers the common questions and most answers are available instantly through search.' }, { heading: 'Still stuck?', body: 'Contact support from within any product or email support@afuchat.com. We respond within 4 hours on business days.' }, { heading: 'Enterprise support', body: 'Enterprise customers have a dedicated support channel with a guaranteed 1 hour response SLA.' }] },
  sitemap: { accent: '#91a8c4', illustration: illSecSitemap, intro: 'A complete directory of the AfuChat corporate site, product ecosystem, and resources.', sections: [{ heading: 'Find your way around', body: 'Explore products, company information, developer resources, and legal documentation.' }, { heading: 'Need something else?', body: 'If you cannot find a page, visit our Help Center or contact the team directly.' }] },
  privacy: { accent: '#4da8ff', intro: 'How we collect, use, and protect your data.', sections: [{ heading: 'Information we collect', body: 'We collect information to provide better services, including account details and usage data when you interact with our products.' }, { heading: 'How we use your data', body: 'We use information to operate, maintain, and improve services. We do not sell personal data to third parties.' }, { heading: 'Data security', body: 'We implement industry standard security measures, including end to end encryption where applicable.' }] },
  terms: { accent: '#9d8cff', intro: 'The rules and responsibilities that govern use of our products and platform.', sections: [{ heading: 'Acceptance of terms', body: 'By accessing our products, you agree to be bound by these Terms of Service.' }, { heading: 'User responsibilities', body: 'You are responsible for use of the services and for keeping account information accurate and secure.' }, { heading: 'Service modifications', body: 'We may modify or discontinue services and will provide reasonable notice of significant changes whenever possible.' }] },
};

export default function GenericPage({ title, type }: GenericPageProps) {
  const content = PAGE_CONTENT[type.toLowerCase()] ?? PAGE_CONTENT.about;
  const isLegal = ['privacy', 'terms'].includes(type.toLowerCase());
  return <div className="studio-shell">
    <section className="max-container studio-section grid items-center gap-12 lg:grid-cols-[1fr_.76fr] lg:gap-24"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}><p className="studio-kicker mb-6" style={{ color: content.accent }}>AfuChat / {type}</p><h1 className="max-w-3xl text-[clamp(3.5rem,8vw,7.5rem)] font-semibold leading-[.88] tracking-[-.075em] text-[#e6f1ff]">{title}</h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-[#91a8c4]">{content.intro}</p></motion.div>{content.illustration && <motion.div initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .1 }} className="p-6"><img src={content.illustration} alt={title} className="w-full" /></motion.div>}</section>
    <section><div className="max-container studio-section grid gap-12 lg:grid-cols-[.42fr_1fr] lg:gap-24"><div><p className="studio-kicker" style={{ color: content.accent }}>The brief</p></div><div>{content.sections.map((section, index) => <motion.article key={section.heading} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .06 }} className="grid gap-4 py-8 sm:grid-cols-[.34fr_1fr]"><h2 className="text-xl font-semibold text-[#e6f1ff]">{section.heading}</h2><p className="text-sm leading-relaxed text-[#91a8c4]">{section.body}</p></motion.article>)}</div></div></section>
    {!isLegal && <section className="max-container studio-section-tight"><div className="mb-8 flex items-end justify-between"><div><p className="studio-kicker mb-4" style={{ color: content.accent }}>Product system</p><h2 className="text-3xl font-semibold text-[#e6f1ff]">Explore the ecosystem.</h2></div><Link href="/products" className="studio-link flex items-center gap-2 text-xs">All products <ArrowUpRight className="h-3.5 w-3.5" /></Link></div><div className="grid border-t border-white/10 sm:grid-cols-2 lg:grid-cols-4">{PRODUCT_DATA.slice(0, 4).map((product) => { const Icon = product.icon; return <Link key={product.id} href={product.path} className="group flex items-center gap-3 border-b border-white/10 px-2 py-5 sm:border-l sm:px-5 first:sm:border-l-0"><Icon className="h-5 w-5" style={{ color: product.color }} strokeWidth={1.5} /><span className="text-sm text-[#91a8c4] group-hover:text-white">{product.name}</span><ArrowUpRight className="ml-auto h-3.5 w-3.5 text-[#5d7694] group-hover:text-[#4da8ff]" /></Link>; })}</div></section>}
    <section className="max-container pb-24"><div className="studio-panel flex flex-col items-start justify-between gap-7 p-8 sm:flex-row sm:items-center sm:p-10"><div><p className="studio-kicker mb-4" style={{ color: content.accent }}>Next step</p><h2 className="text-2xl font-semibold text-[#e6f1ff]">Need to talk through something?</h2></div><Link href="/contact" className="studio-button studio-button-ghost">Contact the studio <ArrowUpRight className="h-4 w-4" /></Link></div></section>
    <Footer />
  </div>;
}