'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowUpRight, Rocket, ShieldCheck, Target, Users } from 'lucide-react';
import { illSecContact, illSecEcosystem } from '@/data/illustrations';
import Link from 'next/link';
import Footer from '@/components/layout/Footer';

const benefits = [
  { icon: Users, color: '#f5b84b', label: 'Reach', desc: 'Gain exposure across a growing family of independent products.' },
  { icon: Target, color: '#4da8ff', label: 'Co-marketing', desc: 'Work with us on launches, case studies, and useful stories.' },
  { icon: ShieldCheck, color: '#8be7c4', label: 'Technical support', desc: 'Get direct access to our engineering team and partner APIs.' },
  { icon: Rocket, color: '#9d8cff', label: 'Revenue share', desc: 'Create a sustainable channel through reseller programs.' },
];

export default function Partners() {
  const [submitted, setSubmitted] = useState(false);
  return <div className="studio-shell">
    <section className="max-container studio-section grid items-center gap-12 lg:grid-cols-[1fr_.86fr] lg:gap-24">
      <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}><p className="studio-kicker mb-6 text-[#f5b84b]">Partner program / Open invitation</p><h1 className="max-w-3xl text-[clamp(3.4rem,7.5vw,7rem)] font-semibold leading-[.88] tracking-[-.075em] text-[#e6f1ff]">Build the<br /><span className="text-[#f5b84b]">next layer</span><br />with us.</h1><p className="mt-8 max-w-xl text-base leading-relaxed text-[#91a8c4] sm:text-lg">Integrate your technology, reach new users, or bring AfuChat products to the organizations you serve. We are looking for thoughtful partners who value craft, speed, and privacy.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#apply" className="studio-button text-[#06101f] bg-[#f5b84b] hover:bg-[#ffd170]">Apply to partner <ArrowUpRight className="h-4 w-4" /></a><Link href="/contact" className="studio-button studio-button-ghost">Contact team</Link></div></motion.div>
       <div><img src={illSecEcosystem} alt="AfuChat partner ecosystem" className="w-full" /><div className="mt-5 pt-4 text-[10px] text-[#5d7694] studio-mono">PARTNERS / SHARED MOMENTUM</div></div>
    </section>
    <section className="border-y border-white/[.08] bg-[#081529]/55"><div className="max-container studio-section-tight"><p className="studio-kicker mb-5 text-[#f5b84b]">Why partner</p><h2 className="max-w-2xl text-3xl font-semibold text-[#e6f1ff] sm:text-4xl">The best work has more than one point of view.</h2><div className="mt-10 grid border-t border-white/10 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(({ icon: Icon, color, label, desc }, index) => <motion.div key={label} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }} className="border-b border-white/10 p-6 lg:border-l lg:first:border-l-0"><Icon className="h-5 w-5" style={{ color }} strokeWidth={1.5} /><h3 className="mt-9 text-sm font-semibold text-[#e6f1ff]">{label}</h3><p className="mt-3 text-sm leading-relaxed text-[#6f89a7]">{desc}</p></motion.div>)}</div></div></section>
    <section className="max-container studio-section-tight"><div className="mb-10"><p className="studio-kicker mb-5 text-[#f5b84b]">Programs</p><h2 className="text-3xl font-semibold text-[#e6f1ff] sm:text-4xl">Choose your lane.</h2></div><div className="grid border-t border-white/10 md:grid-cols-3">{[['Technology partners', '#4da8ff', 'Integrate your software with our APIs. Best for SaaS tools, identity providers, and extensions.'], ['Reseller partners', '#8be7c4', 'Sell our products to your clients. For MSPs, IT consultancies, and system integrators.'], ['Media partners', '#f5b84b', 'Collaborate on content distribution via AfuNews and AfuMovies. For publishers and creators.']].map(([title, color, desc]) => <div key={title} className="border-b border-white/10 p-6 md:border-l md:first:border-l-0 sm:p-8"><h3 className="text-lg font-semibold" style={{ color }}>{title}</h3><p className="mt-4 text-sm leading-relaxed text-[#6f89a7]">{desc}</p><a href="#apply" className="mt-7 inline-flex items-center gap-2 text-xs text-[#91a8c4] hover:text-white">Apply now <ArrowUpRight className="h-3.5 w-3.5" /></a></div>)}</div></section>
     <section id="apply" className="border-t border-white/[.08] bg-[#081529]/55"><div className="max-container studio-section grid gap-12 lg:grid-cols-[1fr_.72fr] lg:gap-24"><div><p className="studio-kicker mb-5 text-[#f5b84b]">Start a conversation</p><h2 className="text-3xl font-semibold text-[#e6f1ff] sm:text-5xl">Let&apos;s find the<br />shared opportunity.</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-[#6f89a7]">Tell us about your organization and how we can work together. Our team will get back to you within two business days.</p>{submitted ? <div className="mt-8 border border-[#8be7c4]/40 bg-[#8be7c4]/[.06] p-5 text-sm text-[#8be7c4]">Thanks, your interest is noted. We&apos;ll be in touch soon.</div> : <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }} className="mt-8 grid gap-3"><input required type="text" placeholder="Company name" className="border border-white/10 bg-[#06101f] px-4 py-3 text-sm text-white outline-none placeholder:text-[#5d7694] focus:border-[#f5b84b]" /><input required type="email" placeholder="Work email" className="border border-white/10 bg-[#06101f] px-4 py-3 text-sm text-white outline-none placeholder:text-[#5d7694] focus:border-[#f5b84b]" /><select required defaultValue="" className="border border-white/10 bg-[#06101f] px-4 py-3 text-sm text-[#91a8c4] outline-none focus:border-[#f5b84b]"><option value="" disabled>Partnership type</option><option value="tech">Technology partner</option><option value="reseller">Reseller partner</option><option value="media">Media partner</option></select><textarea required placeholder="How would you like to partner?" rows={4} className="resize-none border border-white/10 bg-[#06101f] px-4 py-3 text-sm text-white outline-none placeholder:text-[#5d7694] focus:border-[#f5b84b]" /><button type="submit" className="studio-button w-fit bg-[#f5b84b] text-[#06101f]">Submit application <ArrowUpRight className="h-4 w-4" /></button></form>}</div><img src={illSecContact} alt="Contact AfuChat Technologies" loading="lazy" className="mx-auto hidden w-full max-w-xs self-center lg:block" /></div></section>
    <Footer />
  </div>;
}