'use client';

import { motion } from 'framer-motion';
import { ExternalLink, Star, ArrowUpRight } from 'lucide-react';
import Footer from '@/components/layout/Footer';
import { TRUSTPILOT_PROFILE_URL, TRUSTPILOT_REVIEWS, TRUSTPILOT_SUMMARY, type TrustpilotReview } from '@/data/trustpilot';
import ScrollReveal from '@/components/motion/ScrollReveal';

function initials(name: string) { return name.split(' ').filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join(''); }
function Stars({ rating }: { rating: number }) { return <div className="flex gap-1">{[1, 2, 3, 4, 5].map((star) => <Star key={star} className={`h-3.5 w-3.5 ${star <= rating ? 'fill-[#8be7c4] text-[#8be7c4]' : 'fill-transparent text-[#5d7694]'}`} />)}</div>; }
function ReviewCard({ review }: { review: TrustpilotReview }) {
  return <a href={review.url} target="_blank" rel="noopener noreferrer" className="site-card group flex w-[320px] shrink-0 flex-col p-6 sm:w-[370px]"><Stars rating={review.rating} /><h2 className="mt-5 text-lg font-semibold leading-snug text-[#e6f1ff]">{review.title}</h2><p className="mt-3 flex-1 text-sm leading-relaxed text-[#91a8c4]">&quot;{review.quote}&quot;</p><div className="mt-7 flex items-center justify-between border-t border-white/10 pt-5"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center bg-[#257bd1] text-[10px] font-semibold text-white">{initials(review.author)}</span><div><p className="text-xs font-semibold text-[#e6f1ff]">{review.author}</p><p className="mt-1 text-[10px] text-[#5d7694]">{review.country} · {review.date}</p></div></div><ExternalLink className="h-3.5 w-3.5 text-[#5d7694] transition-colors group-hover:text-[#4da8ff]" /></div></a>;
}

export default function Reviews() {
  const middle = Math.ceil(TRUSTPILOT_REVIEWS.length / 2);
  const rows = [TRUSTPILOT_REVIEWS.slice(0, middle), TRUSTPILOT_REVIEWS.slice(middle)];
  return <div className="studio-shell atmosphere-page">
    <section className="page-hero max-container studio-section"><div className="grid items-end gap-10 lg:grid-cols-[1fr_.7fr]"><div><div className="accent-bar mb-7" /><motion.p initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="studio-kicker mb-6 text-[#087a68]">Customer stories / Public record</motion.p><motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .06 }} className="max-w-3xl text-[clamp(3.5rem,8vw,7.5rem)] font-semibold leading-[.88] tracking-[-.075em] text-[#e6f1ff]">Words from<br /><span className="text-[#087a68]">the field.</span></motion.h1></div><div><p className="text-base leading-relaxed text-[#91a8c4]">We don&apos;t write these ourselves. Every review below is public and verifiable on Trustpilot.</p><a href={TRUSTPILOT_PROFILE_URL} target="_blank" rel="noopener noreferrer" className="color-panel mt-6 inline-flex items-center gap-4 rounded-2xl px-5 py-4 hover:border-[#8be7c4]/50"><span className="text-2xl font-semibold text-[#e6f1ff]">{TRUSTPILOT_SUMMARY.rating.toFixed(1)}</span><span><Stars rating={Math.round(TRUSTPILOT_SUMMARY.rating)} /><span className="mt-1 block text-[10px] text-[#5d7694]">{TRUSTPILOT_SUMMARY.reviewCount} reviews on Trustpilot</span></span><ArrowUpRight className="h-4 w-4 text-[#8be7c4]" /></a></div></div></section>
     <section className="atmosphere-band overflow-hidden py-12"><ScrollReveal className="mb-8 max-container"><p className="studio-kicker text-[#d76750]">Unedited / Unfiltered</p><p className="mt-3 max-w-xl text-sm leading-relaxed text-[#6f89a7]">Real words from people using AfuChat products in their day-to-day work and communication.</p></ScrollReveal><div className="flex w-max gap-5 px-4 studio-marquee">{[...rows[0], ...rows[0]].map((review, index) => <ReviewCard key={`a-${index}`} review={review} />)}</div><div className="mt-5 flex w-max gap-5 px-4" style={{ animation: 'studio-marquee 42s linear infinite reverse' }}>{[...rows[1], ...rows[1]].map((review, index) => <ReviewCard key={`b-${index}`} review={review} />)}</div></section>
     <section className="max-container py-24"><div className="color-panel rounded-[1.8rem] flex flex-col items-start justify-between gap-8 p-8 sm:flex-row sm:items-end sm:p-12"><div><p className="studio-kicker mb-5 text-[#4da8ff]">Your turn</p><h2 className="text-3xl font-semibold text-[#e6f1ff] sm:text-4xl">Have a useful thing<br />in mind?</h2></div><a href="https://web.afuchat.com/register" className="studio-button studio-button-primary">Create a free account <ArrowUpRight className="h-4 w-4" /></a></div></section>
    <Footer />
  </div>;
}